<?php

require 'Utils.php';
require 'Neighbor.php';

$filename = "1118";
$sequences = [
    "TTCTGGGTCACGGTGCTAGGGG",
    "ATTTTCCCTATTCATCCAGGGAAAATGTTATGTT",
    "TTTGTGAAGGCTTCGCAGGTACGTGAAAACCCATCCG",
    "AATTTTTGTTGTCAAAGCAGCTTCCTAATGGAGGGTGGGGAG",
    "TGTTGTCACTTATGCGTGCTGGGCAGGCTGAGATAGATCCGACAC",
    "ACAAAATCCTGATGGGTCTTGGTATGGTTGCTGGGGAATTTGCTACACT",
    "ACATAGAGGGTCATAGTACCATGTTTGGATCTGCATTGAGCTACATTGCA",
    "AGGATGAGACCACTAGGTACCTTTGCATTGGAAGTGTAGAGAAGGTGTTATA",
    "TTTATGAGTGGTCAGGGTGCAATCCCCTTCCACCAGAGTTCTGGCTTCTACCCAAA",
    "GCAGGCCCATTATTCTTCGTTCAACCTTTGGTAATGGCACTGTACATTACAGGATCCCTTGA",
    "TCTTTGAAGAAACTCTGATTGAGAGGGAGTATGTAGAGTGCACTGGTTCAGCAATGCAAGCCCTGGC",
    "TGTAGGCCCAATCACTGCCTTAGTCAGATCACTAAGAAAAGAATTGTACAATGAGCCTTATGATCGAG",
];

$distances = [];

$neighbor = new Neighbor($distances);
$neighbor->distanceFromSequences($sequences);

$ans = $neighbor->run();

echo "--------------Dendograma:----------";
var_dump($neighbor->dendogram);
$neighbor->dendogram->toDot();
echo "----------------------------------";

$utils = new Utils();

$utils->createFileStar($filename, "distances", $ans["ds"]);
$utils->createFileStar($filename, "qs", $ans["qs"]);