<?php

require 'Star.php';

$name = "8";
//$sequences = array(
//    "ATTGCCATT",
//    "ATGGCCATT",
//    "ATCCAATTTT",
//    "ATCTTCTT",
//    "ACTGACC"
//);

$sequences = [
    "CAAATGCAGGGACACCACA",
    "TTCTGGGTCACGGTGCTAGGGG",
    "AGCAGCAATGGTGGTTTCCCTGCTTGGGAGCC",
    "ATTTTCCCTATTCATCCAGGGAAAATGTTATGTT",
    "TGAAGAGTATGGACCAACATTAAAGAAAGCACACCAC",
    "TTTGTGAAGGCTTCGCAGGTACGTGAAAACCCATCCG",
    "ATGTGGAAGTTGAAGGTAGCAGAAGGAGGAAAAGGGT",
    "AATTTTTGTTGTCAAAGCAGCTTCCTAATGGAGGGTGGGGAG",
    "TCAAAGAGCCTACCAATGGTTAGAGAAATTCAATCCAACTGAAT",
    "TGTTGTCACTTATGCGTGCTGGGCAGGCTGAGATAGATCCGACAC",
    "TGGTTTCTGTGAGCAATTTCATCGGAAGGCAACACTGGGTGTTCGACC",
    "ACAAAATCCTGATGGGTCTTGGTATGGTTGCTGGGGAATTTGCTACACT",
    "ACTGTCGCTTAGTTTACATGCCCATGTCATATTTATATGGAAAGAAGTT",
    "ACATAGAGGGTCATAGTACCATGTTTGGATCTGCATTGAGCTACATTGCA",
    "GTGACTTCAAAGCAATGTACAGACACATTTCCAAAGGGGCATGGACATTCTC",
    "AGGATGAGACCACTAGGTACCTTTGCATTGGAAGTGTAGAGAAGGTGTTATA",
    "TTGAGGGTACTTGGACAAAGCCTTGAAGATGGTGAGGACATGGCAGTGGCCA",
    "TTTATGAGTGGTCAGGGTGCAATCCCCTTCCACCAGAGTTCTGGCTTCTACCCAAA",
    "GAGGCAGAAAATGGATCCTCGATCATGGCGGTTTAGTAGCTATTCCATCATGGGGAAAG",
    "GCAGGCCCATTATTCTTCGTTCAACCTTTGGTAATGGCACTGTACATTACAGGATCCCTTGA",
    "AATGCAGCTGAGAAAGGAGAACCCTTGTGGGCCCATCCCACCAGCAGTTAAATTGAGAGATGTG",
    "TCTTTGAAGAAACTCTGATTGAGAGGGAGTATGTAGAGTGCACTGGTTCAGCAATGCAAGCCCTGGC",
    "AATGCATGATCATGGATGGCAAGTCTCTGATTGCACAGCAGAAGGACTAAAGGTTGCACTCCTACTG",
    "TGTAGGCCCAATCACTGCCTTAGTCAGATCACTAAGAAAAGAATTGTACAATGAGCCTTATGATCGAG",
    "CAATTCACCGTGGAATAAGGTTACTCATTAATTCACAAATGGATGATGGAGACTTCCCACAACAGGAGAT"
];

$star = new Star();
$star->setSequences($sequences);
$star->calcule($name);

